// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBxrSDNX33jNw8JLIK_TMKpvvsVNsMF2E',
    appId: '1:126659013156:web:f40bf674115fb826a246b1',
    messagingSenderId: '126659013156',
    projectId: 'bulu-flutter-quiz',
    authDomain: 'bulu-flutter-quiz.firebaseapp.com',
    storageBucket: 'bulu-flutter-quiz.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUpYerZ6Y2IvyZ-nElED4Rn3aG1C_82eM',
    appId: '1:126659013156:android:0c2a5ec6bc3e8377a246b1',
    messagingSenderId: '126659013156',
    projectId: 'bulu-flutter-quiz',
    storageBucket: 'bulu-flutter-quiz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8oNBfNp3kg8xru5sKfiBP9x3OaTsKkfw',
    appId: '1:126659013156:ios:49d6b0bcc66abe81a246b1',
    messagingSenderId: '126659013156',
    projectId: 'bulu-flutter-quiz',
    storageBucket: 'bulu-flutter-quiz.appspot.com',
    iosClientId: '126659013156-sls90rgrt8ke5vreijpvuqsvmocu7m71.apps.googleusercontent.com',
    iosBundleId: 'io.bulu.flutterQuiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8oNBfNp3kg8xru5sKfiBP9x3OaTsKkfw',
    appId: '1:126659013156:ios:49d6b0bcc66abe81a246b1',
    messagingSenderId: '126659013156',
    projectId: 'bulu-flutter-quiz',
    storageBucket: 'bulu-flutter-quiz.appspot.com',
    iosClientId: '126659013156-sls90rgrt8ke5vreijpvuqsvmocu7m71.apps.googleusercontent.com',
    iosBundleId: 'io.bulu.flutterQuiz',
  );
}
